### ISSUE TITLE
ImportError: No module named 'misp_stix_converter.servers'

### ISSUE THREAD

**Issue by jpferrero** [MISP/MISP-STIX-Converter#4]
Hello,

Since last update I get the following error when launching stix-to-misp.py and misp-to-stix.py:

ImportError: No module named 'misp_stix_converter.servers'

All dependecies seems to be installed:

#####################

> stix-to-misp.py 
Traceback (most recent call last):
  File "/usr/local/bin/stix-to-misp.py", line 4, in <module>
    __import__('pkg_resources').run_script('Stix-MISP-Converter==0.2', 'stix-to-misp.py')
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 534, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 1445, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python3.4/dist-packages/Stix_MISP_Converter-0.2-py3.4.egg/EGG-INFO/scripts/stix-to-misp.py", line 15, in <module>
ImportError: No module named 'misp_stix_converter.servers'
> pip3 list | grep -i stix
stix (1.2.0.1)
Stix-MISP-Converter (0.2)
>
############################

Thanks,

**Comment by FloatingGhost** [comment]
Yep, there was a problem with the setup.py

Fixed :)
